-- Run this in your Supabase SQL Editor

-- 1. Create Likes Table
create table if not exists likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  component_id uuid references components(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, component_id)
);

-- 2. Enable Row Level Security
alter table likes enable row level security;

-- 3. Create Policies
-- Allow anyone to read likes (to show counts)
create policy "Likes are viewable by everyone" 
on likes for select 
using ( true );

-- Allow authenticated users to like a component
create policy "Authenticated users can insert likes" 
on likes for insert 
with check ( auth.uid() = user_id );

-- Allow users to unlike (delete) their own likes
create policy "Users can delete their own likes" 
on likes for delete 
using ( auth.uid() = user_id );
