-- Run this in your Supabase SQL Editor

-- ============================================
-- 1. Create Likes Table (Fixed for static components)
-- ============================================
-- NOTE: component_id is TEXT to support both static integer IDs and dynamic UUIDs

-- Drop existing table if you need to recreate (CAREFUL: this deletes all likes!)
-- drop table if exists likes;

create table if not exists likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  component_id text not null, -- TEXT to support both static (1,2,3) and dynamic (UUID) component IDs
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, component_id)
);

-- Create index for faster queries
create index if not exists likes_component_id_idx on likes(component_id);
create index if not exists likes_user_id_idx on likes(user_id);

-- Enable Row Level Security
alter table likes enable row level security;

-- Drop existing policies if they exist (for updates)
drop policy if exists "Likes are viewable by everyone" on likes;
drop policy if exists "Authenticated users can insert likes" on likes;
drop policy if exists "Users can delete their own likes" on likes;

-- Likes Policies
create policy "Likes are viewable by everyone" 
on likes for select 
using ( true );

create policy "Authenticated users can insert likes" 
on likes for insert 
with check ( auth.uid() = user_id );

create policy "Users can delete their own likes" 
on likes for delete 
using ( auth.uid() = user_id );

-- ============================================
-- 2. Create Favorites/Saved Table
-- ============================================
-- Drop existing table if you need to recreate (CAREFUL: this deletes all favorites!)
-- drop table if exists favorites;

create table if not exists favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  component_id text not null, -- TEXT to support both static and dynamic component IDs
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, component_id)
);

-- Create index for faster queries
create index if not exists favorites_component_id_idx on favorites(component_id);
create index if not exists favorites_user_id_idx on favorites(user_id);

-- Enable Row Level Security
alter table favorites enable row level security;

-- Drop existing policies if they exist (for updates)
drop policy if exists "Users can view their own favorites" on favorites;
drop policy if exists "Authenticated users can add favorites" on favorites;
drop policy if exists "Users can remove their own favorites" on favorites;

-- Favorites Policies
create policy "Users can view their own favorites" 
on favorites for select 
using ( auth.uid() = user_id );

create policy "Authenticated users can add favorites" 
on favorites for insert 
with check ( auth.uid() = user_id );

create policy "Users can remove their own favorites" 
on favorites for delete 
using ( auth.uid() = user_id );

-- ============================================
-- MIGRATION: Fix existing likes table if it has UUID type
-- ============================================
-- Run this ONLY if you have an existing likes table with uuid component_id:
-- 
-- Step 1: Create a backup
-- CREATE TABLE likes_backup AS SELECT * FROM likes;
--
-- Step 2: Drop existing table and recreate
-- DROP TABLE likes;
-- Then run the CREATE TABLE statement above
--
-- OR use ALTER to change type (if no foreign key constraint):
-- ALTER TABLE likes ALTER COLUMN component_id TYPE text;

-- ============================================
-- 3. Add Creator Info to Components Table
-- ============================================
-- If the components table already exists, add these columns:
alter table components add column if not exists creator_name text;
alter table components add column if not exists creator_avatar text;
alter table components add column if not exists creator_url text;
alter table components add column if not exists is_template boolean default false;

-- ============================================
-- 4. Create Templates Table (for Full Page Templates)
-- ============================================
create table if not exists templates (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  description text,
  category text not null default 'landing',
  tags text[] default '{}',
  html text not null,
  css text not null,
  js text,
  preview_url text,
  creator_id uuid references auth.users,
  creator_name text,
  creator_avatar text,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table templates enable row level security;

-- Templates Policies
create policy "Templates are viewable by everyone" 
on templates for select 
using ( status = 'approved' or auth.uid() = creator_id );

create policy "Authenticated users can submit templates" 
on templates for insert 
with check ( auth.uid() = creator_id );

create policy "Users can update their own templates" 
on templates for update 
using ( auth.uid() = creator_id );
