-- Run this in your Supabase SQL Editor

-- ============================================
-- 1. Create Likes Table
-- ============================================
create table if not exists likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  component_id uuid references components(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, component_id)
);

-- Enable Row Level Security
alter table likes enable row level security;

-- Likes Policies
create policy "Likes are viewable by everyone" 
on likes for select 
using ( true );

create policy "Authenticated users can insert likes" 
on likes for insert 
with check ( auth.uid() = user_id );

create policy "Users can delete their own likes" 
on likes for delete 
using ( auth.uid() = user_id );

-- ============================================
-- 2. Create Favorites/Saved Table
-- ============================================
create table if not exists favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  component_id text not null, -- Can be UUID or static component ID
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, component_id)
);

-- Enable Row Level Security
alter table favorites enable row level security;

-- Favorites Policies
create policy "Users can view their own favorites" 
on favorites for select 
using ( auth.uid() = user_id );

create policy "Authenticated users can add favorites" 
on favorites for insert 
with check ( auth.uid() = user_id );

create policy "Users can remove their own favorites" 
on favorites for delete 
using ( auth.uid() = user_id );

-- ============================================
-- 3. Add Creator Info to Components Table
-- ============================================
-- If the components table already exists, add these columns:
alter table components add column if not exists creator_name text;
alter table components add column if not exists creator_avatar text;
alter table components add column if not exists creator_url text;
alter table components add column if not exists is_template boolean default false;

-- ============================================
-- 4. Create Templates Table (for Full Page Templates)
-- ============================================
create table if not exists templates (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  description text,
  category text not null default 'landing',
  tags text[] default '{}',
  html text not null,
  css text not null,
  js text,
  preview_url text,
  creator_id uuid references auth.users,
  creator_name text,
  creator_avatar text,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table templates enable row level security;

-- Templates Policies
create policy "Templates are viewable by everyone" 
on templates for select 
using ( status = 'approved' or auth.uid() = creator_id );

create policy "Authenticated users can submit templates" 
on templates for insert 
with check ( auth.uid() = creator_id );

create policy "Users can update their own templates" 
on templates for update 
using ( auth.uid() = creator_id );
